apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: javalove93/spring-boot-docker
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080

